work_dir: ./work_dir/NTU-RGB-D/xview/ST_GCN

# feeder
feeder: st_gcn.feeder.Feeder
train_feeder_args:
  data_path: tools/data/NTU-RGB-D/xview/train_data.npy
  label_path: tools/data/NTU-RGB-D/xview/train_label.pkl
test_feeder_args:
  data_path: tools/data/NTU-RGB-D/xview/val_data.npy
  label_path: tools/data/NTU-RGB-D/xview/val_label.pkl


# model
model: st_gcn.net.ST_GCN
model_args:
  num_class: 60
  channel: 27
  window_size: 300
  num_point: 24
  num_person: 2
  graph: st_gcn.graph.NTU_RGB_D
  graph_args:
    labeling_mode: 'spatial'
  mask_learning: True
  use_data_bn: True 

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 8
test_batch_size: 8
num_epoch: 80
nesterov: True



