base_lr: 0.1
batch_size: 8
config: config/st_gcn/nturgbd-cross-view/train.yaml
device: [0]
display_by_category: false
display_recall_precision: false
eval_interval: 1
feeder: st_gcn.feeder.Feeder
ignore_weights: []
log_interval: 100
model: st_gcn.net.ST_GCN
model_args:
  channel: 27
  graph: st_gcn.graph.NTU_RGB_D
  graph_args: {labeling_mode: spatial}
  mask_learning: true
  num_class: 60
  num_person: 2
  num_point: 24
  use_data_bn: true
  window_size: 300
nesterov: true
num_epoch: 80
num_worker: 128
optimizer: SGD
phase: train
print_log: true
save_interval: 1
save_score: false
seed: 1
show_topk: [1, 5]
start_epoch: 0
step: [10, 50]
test_batch_size: 8
test_feeder_args: {data_path: tools/data/NTU-RGB-D/xview/val_data.npy, label_path: tools/data/NTU-RGB-D/xview/val_label.pkl}
train_feeder_args: {data_path: tools/data/NTU-RGB-D/xview/train_data.npy, label_path: tools/data/NTU-RGB-D/xview/train_label.pkl}
weight_decay: 0.0001
weights: null
work_dir: dir_view
